#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
killall -q dunst
killall -q picom

xsetroot -cursor_name left_ptr

# startup
picom --config ~/.config/picom/picom.conf &
dunst -config ~/.config/dunst/dunstrc &
sh ~/.config/polybar/launch.sh &
nitrogen --restore &
nm-applet &
parcellite &

telegram-desktop &
steam &
Google-chrome &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 1
bspc config window_gap 4

#cursor follow
bspc config focus_follows_pointer true

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Google-chrome desktop=^2 follow=on
bspc rule -a TelegramDesktop desktop=^4 state=pseudo_tiled center=on follow=on
bspc rule -a steam desktop=^3
bspc rule -a Spotify desktop=^3
bspc rule -a TelegramDesktop title="Media viewer" state=fullscreen
