#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

xsetroot -cursor_name left_ptr

# startup
sh ~/.config/polybar/launch.sh
nitrogen --restore &
xwinwrap -b -s -fs -st -sp -nf -ov -fdt -- mpv --wid $(xwininfo -root | grep 'Window id:' | awk '{print $4}') --really-quiet --framedrop=vo --no-audio --panscan="1.0" ~/Videos/lofi-rainy-lifestyle.mp4 &

telegram-desktop &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 1
bspc config window_gap 4

#cursor follow
bspc config focus_follows_pointer true

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Google-chrome-unstable desktop=^2 follow=on
bspc rule -a TelegramDesktop desktop=^3 state=pseudo_tiled center=on follow=on
bspc rule -a "Media viewer" state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
