#! /bin/sh

# kill all processes
pgrep -x sxhkd >/dev/null || sxhkd &
killall -q dunst
pkill picom
picom --experimental-backends &

pkill -f ~/.config/dunst/battery-notify.sh &
pkill -f ~/.config/dunst/volume-notify.sh &
pkill -f ~/.config/dunst/brightness-notify.sh &
pkill -f ~/.config/polybar/launch.sh &

# fix cursor
xsetroot -cursor_name left_ptr

# startup
picom --config ~/.config/picom/picom.conf &
dunst -config ~/.config/dunst/dunstrc &
nitrogen --restore &
nm-applet &
parcellite &
ulauncher &

# notifications
sh ~/.config/dunst/battery-notify.sh &
sh ~/.config/dunst/volume-notify.sh &
sh ~/.config/dunst/brightness-notify.sh &
# polybar
sh ~/.config/polybar/launch.sh &
# while true; do
#   pkill -f ~/.config/polybar/launch.sh &
#
#   sh ~/.config/polybar/launch.sh &
#   slep 5
# done

telegram-desktop &
steam &
google-chrome &

# bspc monitor -d 1 2 3 4 5 6

bspc config border_width 1
bspc config window_gap 4

#cursor follow
bspc config focus_follows_pointer true

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Google-chrome desktop=^2 follow=on
bspc rule -a TelegramDesktop desktop=^4 state=pseudo_tiled center=on follow=on
bspc rule -a steam desktop=^3
bspc rule -a Spotify desktop=^3
bspc rule -a TelegramDesktop title="Media viewer" state=fullscreen
